global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'
    - match:
        severity: warning
      receiver: 'warning-receiver'

receivers:
  - name: 'default-receiver'
    slack_configs:
      - api_url: '${DEFAULT_SLACK}'
        channel: '#default-notification'
        send_resolved: true
        title: ':information_source: [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* `{{ .Labels.alertname }}`
          *Severity:* `{{ .Labels.severity }}`
          *Service:* `{{ or .Labels.application .Labels.job }}`
          *Instance:* `{{ or .Labels.instance "N/A" }}`
          *Description:* {{ .Annotations.description }}
          *Started At:* {{ .StartsAt.Local.Format "2006-01-02 15:04:05" }}
          {{ end }}
          <{{ .ExternalURL }}|View in Alertmanager>

  - name: 'critical-receiver'
    slack_configs:
      - api_url: '${CRITICAL_SLACK}'
        channel: '#critical-notification'
        send_resolved: true
        title: ':rotating_light: [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Service:* `{{ or .Labels.application .Labels.job }}`
          *Instance:* `{{ or .Labels.instance "N/A" }}`
          *Severity:* `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Started At:* {{ .StartsAt.Local.Format "2006-01-02 15:04:05" }}
          {{ end }}
          <{{ .ExternalURL }}|View in Alertmanager>

  - name: 'warning-receiver'
    slack_configs:
      - api_url: '${WARNING_SLACK}'
        channel: '#warning-notification'
        send_resolved: true
        title: ':warning: [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Service:* `{{ or .Labels.application .Labels.job }}`
          *Instance:* `{{ or .Labels.instance "N/A" }}`
          *Severity:* `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Started At:* {{ .StartsAt.Local.Format "2006-01-02 15:04:05" }}
          {{ end }}
          <{{ .ExternalURL }}|View in Alertmanager>

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
