global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
 - "service-alerts.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Pushgateway (Push Mode)
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  # Gateway Server
  - job_name: 'gateway-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'gateway-server-1:8080'
          - 'gateway-server-2:8081'

  # Eureka Server
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'eureka-server-1:3150'
          - 'eureka-server-2:3151'

  # Config Server
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-server:3100']

  # RabbitMQ (Prometheus 플러그인 활성화 시)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  # 동적으로 Eureka에서 서비스 발견 (마이크로서비스용)
  - job_name: 'microservices'
    eureka_sd_configs:
      - server: 'http://eureka-server-1:3150/eureka'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_path]
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_eureka_app_instance_metadata_prometheus_port]
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
